### ISSUE TITLE
Black Screen with GVRPanoramaView

### ISSUE THREAD

**Issue by humingw** [googlevr/gvr-ios-sdk#112]
X-Code 7.3
iOS 9.3.5, Iphone 6
GVRSDK 0.9.0

I have a UICollectionView where `GVRPanoramaView` is created to display `.Mono` UIImage (on each cell). No Auto layout  and Autorotate is also disabled. The cardboard button, touch tracking and full screen button are all enabled. After tap the cardboard button and rotate the phone to landscape mode, under working condition, two images are displayed (left and right). However sometimes the screen is black (but those white buttons - go back button, full screen button, the setting button and the separator line in the middle, are visible). It doesn't happen all the time. It is pretty frustrating. I looked at Issue #28 and its workaround (calling `widgetView.subviews[0].setNeedsLayout()` in `didChangeDisplayMode`) doesn't fix the issue.  Here is the debug output for `GVRGlView` when the screen is black:
```
<GVRGlView: 0x1097f7b50; frame = (0 0; 375 667); transform = [6.123233995736766e-17, 1, -1, 6.123233995736766e-17, 0, 0]; autoresize = W+H; gestureRecognizers = <NSArray: 0x10594afa0>; layer = <CAEAGLLayer: 0x110f40b80>>
```
Is there any known issue with `GVRPanoramaView `?  Any suggestion?

**Comment by nathanmartz** [comment]
You can try updating to 0.9.1 but I think our fix for this bug may not have made that version so you may need to wait for the next version (in a few weeks).

**Comment by humingw** [comment]
I tried to update to the 0.9.1 via Podfile:
```
pod 'GVRSDK', '~> 0.9.1'

```
But it said this version is not available. Any idea?

**Comment by humingw** [comment]
Just wanted to update that I tried the latest 1.0.0 SDK and the problem is still happening - sometimes the screen is just black.

**Comment by humingw** [comment]
Any update? Is there any workaround? It's pretty frustrating. I am also attaching [the screen] (url) when it is not working.
![img_0502 3](https://cloud.githubusercontent.com/assets/872515/19306542/09d6216a-902b-11e6-9d6a-211e46fd2387.PNG)

**Comment by humingw** [comment]
Also wanted to point out that I created the view in the storyboard (a subview to the collection cell xib file) and assigned the class `GVRPanoramaView` in the identity inspector. It is also in Swift.

**Comment by sanjayc77** [comment]
Can you try the latest GVRSDK 1.0.1?

**Comment by sanjayc77** [comment]
Also, under UICollectionView, you have to take care of reuse of the UICollectionCellView that is hosting the GVRPanorama view.

**Comment by humingw** [comment]
Thanks for reply. The problem apparently still exists. I create a sample Swift project that demonstrates the problem: https://github.com/humingw/PanoImageViewTest  The cardboard view does not work for every cell. Let me know if you have any problem in reproducing the problem with the code.

**Comment by sanjayc77** [comment]
Thanks for the sample app. I am able to reproduce it. Investigating.

**Comment by sanjayc77** [comment]
This should be fixed and available in the next release.

**Comment by humingw** [comment]
That's great!  I am looking forward to the new release.

**Comment by MarkDKoslow** [comment]
Is there any update on this issue? I'm using the latest version of the GVR SDK and sometimes I get the exact same screen as @humingw when I enter cardboard mode for an item in my tableview. Interestingly, it only happens some of the time, and the same URL can render successfully and unsuccessfully within the same app launch.

Thanks in advance for any insight!

**Comment by humingw** [comment]
Confirmed that the problem still exists. Please use this sample (the one posted originally) to reproduce the issue: https://github.com/humingw/PanoImageViewTest In my test, on #5 cell always a blank screen is always displayed when the cardboard button is pressed (other cells seem fine). Can you make a test version available when you have a fix (so that I can also test it in my app)?

**Comment by MarkDKoslow** [comment]
Any updates here? I'd really like to release my app but this bug has been quite persistent. Thanks!

**Comment by jplongo** [comment]
Same issue on my fresh app. View work first time but is black if I back to element. It seems that google.cardboard thread is already active and don't stop.

Hope quick fix will change it

**Comment by oliverwh** [comment]
the problem happens only to 5th GVRPanoramaView. Then it works well on next items.

**Comment by oliverwh** [comment]
apparently that happens more often if u use more than 2 GVRPanoramaView :(
