### ISSUE TITLE
Duplicate symbols between CardboardSDK and GTMSessionFetcher, is there anyway to fix this ?

### ISSUE THREAD

**Issue by MohammadAllam** [googlevr/gvr-ios-sdk#163]
I'm trying to add GVRSDK to my project but as soon as i add it, linking error appear with multiple duplicates between the GVRSDK and GTMSessionFetcher that is used in my application by another pod.
I can't remove the GTMSessionFetcher as some other pods are using it and i'm not able to remove the referencing of it also from the libCardboardSDK.a.

**Comment by sanjayc77** [comment]
Seems like you have another Google library being linked against your application. Can you confirm that? Also post the linker multiple symbols error.

Thanks

**Comment by MohammadAllam** [comment]
@sanjayc77 yup that's true. the two conflicting libraries are  "Google/SignIn" and "GVRSDK".
and here is part of the conflicts am getting :

'''
duplicate symbol _OBJC_IVAR_$_GTMSessionFetcher._taskPriority in:
    /Users/admin/Documents/XCode Apps/Inysdo/Pods/GVRSDK/Libraries/libCardboardSDK_x86_64.a(GTMSessionFetcher_af1aa7acb3dab4c479c6dcb34bdecd4f.o)
    /Users/admin/Library/Developer/Xcode/DerivedData/Insydo-grfgzsgmpzwyzablqwgdrlithhls/Build/Products/Debug-iphonesimulator/GTMSessionFetcher/libGTMSessionFetcher.a(GTMSessionFetcher.o)
duplicate symbol _OBJC_IVAR_$_GTMSessionFetcher._servicePriority in:
    /Users/admin/Documents/XCode Apps/Inysdo/Pods/GVRSDK/Libraries/libCardboardSDK_x86_64.a(GTMSessionFetcher_af1aa7acb3dab4c479c6dcb34bdecd4f.o)
    /Users/admin/Library/Developer/Xcode/DerivedData/Insydo-grfgzsgmpzwyzablqwgdrlithhls/Build/Products/Debug-iphonesimulator/GTMSessionFetcher/libGTMSessionFetcher.a(GTMSessionFetcher.o)
duplicate symbol _kGTMSessionFetcherElapsedIntervalWithRetriesKey in:
    /Users/admin/Documents/XCode Apps/Inysdo/Pods/GVRSDK/Libraries/libCardboardSDK_x86_64.a(GTMSessionFetcher_af1aa7acb3dab4c479c6dcb34bdecd4f.o)
    /Users/admin/Library/Developer/Xcode/DerivedData/Insydo-grfgzsgmpzwyzablqwgdrlithhls/Build/Products/Debug-iphonesimulator/GTMSessionFetcher/libGTMSessionFetcher.a(GTMSessionFetcher.o)
'''

Thanks in advance.

**Comment by sanjayc77** [comment]
Added to internal bug tracker. Thanks for reporting.

**Comment by sanjayc77** [comment]
I am not sure, but does this help your case: http://stackoverflow.com/questions/2300867/how-can-i-avoid-duplicate-symbol-errors-in-xcode-with-shared-static-libraries

**Comment by mfcanovas** [comment]
Still happening when building Google VR SDK for Unity + Firebase for IOS

**Comment by gerardreches** [comment]
+1

I'm experiencing this error too using Google VR SDK for Unity 1.20 + Firebase Unity SDK 3.0.0

**Comment by jay-neb** [comment]
Any fix for this?

**Comment by gerardreches** [comment]
@jay-neb Yup, take a look at this [stackoverflow question](http://stackoverflow.com/questions/42516646/unity-ios-build-error-duplicate-symbols-when-using-firebase-unity-sdk-google/42823090#42823090).

Also I received this response from the **Firebase Support Center** about this problem:

> Did you see the workaround posted in the Stackoverflow post. Please use that workaround for time being.
> Our engineers are working on the permanent fix for the issue. However, I do not have any timeline or ETA available for it at the moment. 
> 
> Once available this fix will be included in the Firebase and/or Google VR Unity SDKs.
> You can get update of the same in the Release Notes for Firebase and GVR.

**Comment by Boudz78** [comment]
The Problem Still Exists.. The Posted Answer didn't Fix my Problem...Any Help regarding this issue is  appreciated..

**Comment by jay-neb** [comment]
Thank you @gerardreches! It worked for me. The stackoverflow answer is a bit vague. You need to:

1. Create a shell script in the directory that he states, Assets/Plugins/iOS/ (it should be the same directory that contains libgvrunity.a). The shell script should contain the code that he posted and you can call it anything, for example gvr_fix.sh.
2. You have to make the shell script executable by executing the command `chmod a+x gvr_fix.sh` in Terminal.
3. Run the shell script by executing the command `./gvr_fix.sh`
4. This will create a new libgvrunity.a file with the correct settings and place the original libgvrunity.a in  a folder called backup. Take the backup folder out of your Unity project (or just delete the folder) to avoid conflicts while building.
5. Go back to Unity and Build, and when it asks you to Replace or Append, click Replace.
6. Open in Xcode and build.

**Comment by Boudz78** [comment]
@jay-neb Thank You!!!
That was much alot elaborated.As a result, i was able to solve my problem.
Again, Thank you.

**Comment by willian-sisinfo** [comment]
Getting the same error on iOS native development when using Firebase Message along with GVRSDK. Any workaround for this?

**Comment by jay-neb** [comment]
@willian-sisinfo Have you tried what I explained together with the stackoverflow answer?

**Comment by sanjayc77** [comment]
This was fixed in 1.30 version of the SDK. Please verify that you have that version.

**Comment by jonflanders** [comment]
I am using Unity 5.6 - when I build to Xcode I am also getting this error.   I tried removing each library one after another but symbols are missing in the version that gets placed by Unity that are only in the GVRSDK pod.

**Comment by NiclasLovdahl** [comment]
I have the same problem with duplicated symbols using GVRSDK for my Unity VR project. I have tried every proposed solution on the issue. Is there a solution for this or i just have to wait for new release?

`duplicate symbol _OBJC_CLASS_$_DeviceParamsSyncHelper in:
    /Users/niclaslovdahl/Desktop/test-ios/Pods/GVRSDK/Libraries/libGVRSDK.a(DeviceParamsSyncHelper.mm.o)
    /Users/niclaslovdahl/Desktop/test-ios/Libraries/Plugins/iOS/libgvrunity.a(DeviceParamsSyncHelper.mm.o)
duplicate symbol _OBJC_METACLASS_$_DeviceParamsSyncHelper in:
    /Users/niclaslovdahl/Desktop/test-ios/Pods/GVRSDK/Libraries/libGVRSDK.a(DeviceParamsSyncHelper.mm.o)
    /Users/niclaslovdahl/Desktop/test-ios/Libraries/Plugins/iOS/libgvrunity.a(DeviceParamsSyncHelper.mm.o)
ld: 1253 duplicate symbols for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)`

**Comment by SoumyaBasheer** [comment]
I have followed the @jay-neb steps to resolve duplicate symbol issue...Now I am getting the following compilation errors..
Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_GTMSessionFetcherService", referenced from:
      objc-class-ref in libgvrunity.a(ionnetworkhelper.mm.o)
  "_kGTMSessionFetcherStatusDomain", referenced from:
      ___43-[IonNetworkHelper makeRequest:requestPtr:]_block_invoke in libgvrunity.a(ionnetworkhelper.mm.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
Anyone have any idea?

**Comment by SoumyaBasheer** [comment]
@sanjayc77 I still have the duplicate symbol issue....I am using the GoogleVR SDK 1.30 and firebase 3.0..

**Comment by sikhote** [comment]
Seeing the `duplicate symbol` issue when adding the last pod in this `Podfile`:

```
target 'Project' do
  pod 'Yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'Core',
    'BatchedBridge'
  ]
  pod 'Firebase/Core'
  pod 'RNFirebase', :path => '../node_modules/react-native-firebase'
  pod 'GVRSDK'
end
```

This was on a vanilla `create-react-native-app` app that has been ejected (it uses RN 0.45.1). The `Podfile.lock` confirms Firebase v4 and GVRSDK v1.60.0:

```
PODS:
  - Firebase/Core (4.0.3):
    - FirebaseAnalytics (= 4.0.2)
    - FirebaseCore (= 4.0.3)
  - FirebaseAnalytics (4.0.2):
    - FirebaseCore (~> 4.0)
    - FirebaseInstanceID (~> 2.0)
    - GoogleToolboxForMac/NSData+zlib (~> 2.1)
  - FirebaseCore (4.0.3):
    - GoogleToolboxForMac/NSData+zlib (~> 2.1)
  - FirebaseInstanceID (2.0.0):
    - FirebaseCore (~> 4.0)
  - GoogleToolboxForMac/Defines (2.1.0)
  - GoogleToolboxForMac/Logger (2.1.0):
    - GoogleToolboxForMac/Defines (= 2.1.0)
  - GoogleToolboxForMac/NSData+zlib (2.1.0):
    - GoogleToolboxForMac/Defines (= 2.1.0)
  - GTMSessionFetcher/Core (1.1.6)
  - GVRSDK (1.60.0):
    - GoogleToolboxForMac/Logger (= 2.1.0)
    - GTMSessionFetcher/Core (= 1.1.6)
  - React/BatchedBridge (0.45.1):
    - React/Core
    - React/cxxreact_legacy
  - React/Core (0.45.1):
    - Yoga (= 0.45.1.React)
  - React/cxxreact_legacy (0.45.1):
    - React/jschelpers_legacy
  - React/jschelpers_legacy (0.45.1)
  - RNFirebase (2.0.2)
  - Yoga (0.45.1.React)
```

**Comment by snovak** [comment]
I think some comments above are a duplicate of https://github.com/googlevr/gvr-ios-sdk/issues/234 .  If you've recently updated the GoogleVR unitypackage by simply reimporting it, you probably need to delete libgvrunity.a, and all references to it, from your Unity project.
